app:
  name: My app
  description: Welcome to ${app.name}

my:
  greeting: hello world from config server
  list:
    value: One,Two,Three,Four

db:
  connection: "{connectionString: 'http://___', userName: 'foo', password: 'pass'}"
  host: 127.0.0.1
  port: 1200

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: test